[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true
